### PR TITLE
exists & missing filter, close #1027, close #1052, close #1058

### LINKED ISSUE #1027: missing filter
see Version Release 02.12.2015

### LINKED ISSUE #1052: add product search exists filter

### LINKED ISSUE #1058: unconfirmed: for search endpoint errors the request is not shown in the stacktrace

### PR DESCRIPTION
**Pull request by schleichardt**
- add missing filter which excludes elements which have no value for a certain field
- add exists filter which only includes elements which have no value for a certain field
- improve error reporting, now the http request is also shown if a search request and others fail
- it also contains a filter for taxCategory and sku
- add state field to product projection

### CODE REVIEW

**Comment by schleichardt** [comment]
@lauraluiz please review, if you want we can release it also for RC4 today or postpone it

**Comment by lauraluiz** [comment]
Looks good :+1: 
I just have one wish: could you put a UT to make sure you can build exists or missing from a locale of a localized string?

**Comment by schleichardt** [comment]
@lauraluiz you mean integration test?

**Comment by lauraluiz** [comment]
No, I really meant unit tests (no typo there :P), just to make sure the DSL supports exists/missing in:
- field (covered already by category test)
- localized string particular locales
I the current DSL structure is just a string so it's no problem, but I like to have it for future changes, so we don't forget that.
You can write a IT if you like as well, just to make sure the API doesn't lie and we are offering something supported.

**Comment by schleichardt** [comment]
I did an integration test and it works. Great!

**Comment by lauraluiz** [comment]
:+1:

**Pull request merged**
