### PR TITLE
the review statistics are applied asynchronously

### PR DESCRIPTION
**Pull request by yanns**
@schleichardt please review

### CODE REVIEW

**Comment by schleichardt** [comment]
There are flaky tests, but they are not related to this PR, I think:

https://travis-ci.org/sphereio/sphere-jvm-sdk/builds/103721359#L3459
https://travis-ci.org/sphereio/sphere-jvm-sdk/builds/103721453#L3472

**Comment by yanns** [comment]
Yes, I had a look at those, and there was a problem with the authentication.
I trigger them again.

**Comment by yanns** [comment]
Still errors:
```
08:24:04.219 [Thread-58] ERROR sphere.oauth - Failed to fetch token.
java.util.concurrent.CompletionException: io.sphere.sdk.models.SphereException: detailMessage: java.lang.NullPointerException
summary: POST https://auth.sphere.io/oauth/token failed  with response code 200
http response: io.sphere.sdk.http.HttpResponseImpl@56208761[statusCode=200,headers={},associatedRequest=<null>,textInterpretedBody=empty body]
SDK: 1.0.0-RC1-SNAPSHOT
project: a
Java: 1.8.0_60
cwd: /wd
date: Thu Jan 21 08:24:04 UTC 2016
sphere request: <unknown>
http request: HttpRequestImpl[httpMethod=POST,url=https://auth.sphere.io/oauth/token,headers={Authorization=[**removed from output**], User-Agent=[SPHERE.IO JVM SDK 1.0.0-RC1-SNAPSHOT], Content-Type=[application/x-www-form-urlencoded]},body=FormUrlEncodedHttpRequestBody[data=[NameValuePairImpl[name=grant_type,value=client_credentials], NameValuePairImpl[name=scope,value=manage_project:a]]]]
additional notes: []
Javadoc: http://sphereio.github.io/sphere-jvm-sdk/javadoc/1.0.0-RC1-SNAPSHOT/io/sphere/sdk/models/SphereException.html

	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273) ~[na:1.8.0_60]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280) ~[na:1.8.0_60]
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:604) ~[na:1.8.0_60]
	at java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:614) ~[na:1.8.0_60]
	at java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:1983) ~[na:1.8.0_60]
	at java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:110) ~[na:1.8.0_60]
	at io.sphere.sdk.client.TokensSupplierImpl.get(TokensSupplierImpl.java:50) ~[classes/:na]
	at io.sphere.sdk.client.OnDemandSphereAccessTokenSupplier.get(OnDemandSphereAccessTokenSupplier.java:25) ~[classes/:na]
	at io.sphere.sdk.client.OneTimeSphereAccessTokenSupplier.fetchToken(OneTimeSphereAccessTokenSupplier.java:37) ~[classes/:na]
	at io.sphere.sdk.client.OneTimeSphereAccessTokenSupplier.lambda$get$39(OneTimeSphereAccessTokenSupplier.java:29) ~[classes/:na]
	at java.util.Optional.orElseGet(Optional.java:267) ~[na:1.8.0_60]
	at io.sphere.sdk.client.OneTimeSphereAccessTokenSupplier.get(OneTimeSphereAccessTokenSupplier.java:28) ~[classes/:na]
	at io.sphere.sdk.client.TokensSupplierImplTest.httpRequestsContainUserAgents(TokensSupplierImplTest.java:20) ~[test-classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_60]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_60]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_60]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_60]
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47) ~[junit-4.11.jar:na]
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12) ~[junit-4.11.jar:na]
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44) ~[junit-4.11.jar:na]
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17) ~[junit-4.11.jar:na]
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271) ~[junit-4.11.jar:na]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70) ~[junit-4.11.jar:na]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50) ~[junit-4.11.jar:na]
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238) ~[junit-4.11.jar:na]
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63) ~[junit-4.11.jar:na]
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236) ~[junit-4.11.jar:na]
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53) ~[junit-4.11.jar:na]
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229) ~[junit-4.11.jar:na]
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309) ~[junit-4.11.jar:na]
	at org.junit.runners.Suite.runChild(Suite.java:127) ~[junit-4.11.jar:na]
	at org.junit.runners.Suite.runChild(Suite.java:26) ~[junit-4.11.jar:na]
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238) ~[junit-4.11.jar:na]
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63) ~[junit-4.11.jar:na]
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236) ~[junit-4.11.jar:na]
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53) ~[junit-4.11.jar:na]
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229) ~[junit-4.11.jar:na]
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309) ~[junit-4.11.jar:na]
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160) ~[junit-4.11.jar:na]
	at org.junit.runner.JUnitCore.run(JUnitCore.java:138) ~[junit-4.11.jar:na]
	at com.novocode.junit.JUnitRunner$1.execute(JUnitRunner.java:132) ~[junit-interface-0.11.jar:0.11]
	at sbt.TestRunner.runTest$1(TestFramework.scala:76) ~[na:na]
	at sbt.TestRunner.run(TestFramework.scala:85) ~[na:na]
	at sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:202) ~[na:na]
	at sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:202) ~[na:na]
	at sbt.TestFramework$.sbt$TestFramework$$withContextLoader(TestFramework.scala:185) ~[na:na]
	at sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:202) ~[na:na]
	at sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:202) ~[na:na]
	at sbt.TestFunction.apply(TestFramework.scala:207) ~[na:na]
	at sbt.Tests$$anonfun$9.apply(Tests.scala:216) ~[na:na]
	at sbt.Tests$$anonfun$9.apply(Tests.scala:216) ~[na:na]
	at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44) ~[na:na]
	at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44) ~[na:na]
	at sbt.std.Transform$$anon$4.work(System.scala:63) ~[na:na]
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226) ~[na:na]
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226) ~[na:na]
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17) ~[na:na]
	at sbt.Execute.work(Execute.scala:235) ~[na:na]
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226) ~[na:na]
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226) ~[na:na]
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159) ~[na:na]
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28) ~[na:na]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_60]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_60]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_60]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_60]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_60]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_60]
Caused by: io.sphere.sdk.models.SphereException: detailMessage: java.lang.NullPointerException
summary: POST https://auth.sphere.io/oauth/token failed  with response code 200
http response: io.sphere.sdk.http.HttpResponseImpl@56208761[statusCode=200,headers={},associatedRequest=<null>,textInterpretedBody=empty body]
SDK: 1.0.0-RC1-SNAPSHOT
project: a
Java: 1.8.0_60
cwd: /wd
date: Thu Jan 21 08:24:04 UTC 2016
sphere request: <unknown>
http request: HttpRequestImpl[httpMethod=POST,url=https://auth.sphere.io/oauth/token,headers={Authorization=[**removed from output**], User-Agent=[SPHERE.IO JVM SDK 1.0.0-RC1-SNAPSHOT], Content-Type=[application/x-www-form-urlencoded]},body=FormUrlEncodedHttpRequestBody[data=[NameValuePairImpl[name=grant_type,value=client_credentials], NameValuePairImpl[name=scope,value=manage_project:a]]]]
additional notes: []
Javadoc: http://sphereio.github.io/sphere-jvm-sdk/javadoc/1.0.0-RC1-SNAPSHOT/io/sphere/sdk/models/SphereException.html

	at io.sphere.sdk.client.TokensSupplierImpl.parseResponse(TokensSupplierImpl.java:108) ~[classes/:na]
	at io.sphere.sdk.client.TokensSupplierImpl.lambda$get$64(TokensSupplierImpl.java:50) ~[classes/:na]
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602) ~[na:1.8.0_60]
	... 65 common frames omitted
Caused by: java.lang.NullPointerException: null
	at com.fasterxml.jackson.core.JsonFactory.createParser(JsonFactory.java:839) ~[jackson-core-2.6.1.jar:2.6.1]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2824) ~[jackson-databind-2.6.1.jar:2.6.1]
	at io.sphere.sdk.json.SphereJsonUtils.lambda$readObject$51(SphereJsonUtils.java:209) ~[classes/:na]
	at io.sphere.sdk.json.SphereJsonUtils.executing(SphereJsonUtils.java:271) ~[classes/:na]
	at io.sphere.sdk.json.SphereJsonUtils.readObject(SphereJsonUtils.java:209) ~[classes/:na]
	at io.sphere.sdk.client.TokensSupplierImpl.parseResponse(TokensSupplierImpl.java:104) ~[classes/:na]
	... 67 common frames omitted
```
I do not understand why the body of the response is empty.
Have you seen such a (mis-)behaviour before?

**Comment by schleichardt** [comment]
It was a timeout :(

**Comment by schleichardt** [comment]
The other failure was a timeout. 

The empty auth response is weird there were not even headers.

**Comment by schleichardt** [comment]
No, I only got empty auth bodies when something went wrong.

**Pull request merged**
