### PR TITLE
Fix ProductAllVariantsQueryModel is package scope and therefore not usable

### PR DESCRIPTION
**Pull request by schleichardt**

### CODE REVIEW

**Comment by lauraluiz** [comment]
Good catch :disappointed_relieved:

**Comment by schleichardt** [comment]
I wondered why it even compiled.

Another example of: "It works in tests, but not in production."

**Comment by lauraluiz** [comment]
Actually that's the evil side of package scope.

**Comment by schleichardt** [comment]
It is not package scopes fault, if the tests for a public API would not be in the same package then you discover this kind of problems.

Can I merge?

**Comment by lauraluiz** [comment]
Yes, merge it.

**Pull request merged**
