### PR TITLE
Feature/state and item state queries

### PR DESCRIPTION
**Pull request by abrauner**
I hope there are no more mistakes in it. If so I will update the PR. I added some tests according to the channels to create and delete a state. Would be great to get this into the SDK. 

**Note** 
there is a test in CartUpdateCommandTest set to @Ignore because here the ItemState has to be created first to get also a reference. 

Cheers

### CODE REVIEW

**Comment by abrauner** [comment]
Travis complains about missing credentials when I'm right. Is this related to my build? Or a general problem?? Maybe I have to configure something in my Project?

**Comment by schleichardt** [comment]
You work on a different repository, so for security reasons our encrypted credentials cannot be used by you. If the tests are green on your machine, everything is fine, don't worry about travis.

**Comment by schleichardt** [comment]
@abrauner  Thank you very much! Do you want into the hall of fame? https://github.com/sphereio/sphere-jvm-sdk/blob/master/project/Release.scala#L75

**Comment by abrauner** [comment]
Don't know if this is applicable for externals, but if so why not ;-)

**Comment by schleichardt** [comment]
@hajoeichler Is it possible to put him into our hall of fame?

**Comment by hajoeichler** [comment]
We should add a thx notice to the release notes and if @abrauner is further contributing, we will add him to the list of devs ... motivation is everything ;)

**Pull request merged**
