### PR TITLE
Request gzipped responses from sphere. close #873

### LINKED ISSUE #873: Request gzipped responses from sphere

### PR DESCRIPTION
**Pull request by schleichardt**
@lauraluiz please review

### CODE REVIEW

**Comment by lauraluiz** [comment]
How does it work the gzip encoding in whatever-generic-name-has-ning-now? Is it already working for it?

**Comment by lauraluiz** [comment]
Is it possible to write some test for that?

**Comment by schleichardt** [comment]
It is tested through the existing integration tests - for example the Apache thing failed. AHC does unpack automatically.

But I will add a test that checks the response headers so they contain gzip.

**Comment by lauraluiz** [comment]
:+1:

**Pull request merged**
