### PR TITLE
activate discount

### PR DESCRIPTION
**Pull request by yanns**
@schleichardt the test `io.sphere.sdk.products.queries.ProductQueryTest.queryProductsWithAnyDiscount` cannot success with an inactive discount

### CODE REVIEW

**Comment by yanns** [comment]
Oups it seems I broke other tests with this change.

**Comment by yanns** [comment]
The failing tests have to do with the new deprecation from @agourlay

**Comment by schleichardt** [comment]
@agourlay can you give more information for the deprecation, please.

@yanns in team city tests should not fail due to deprecation warnings.

**Comment by schleichardt** [comment]
Thanks Yann, I think I just should not reuse data for performance reasons if the tests behave that weird.

**Comment by agourlay** [comment]
We introduced a HTTP param, on the facet endpoint called formatBooleanFacet.

If the param is provided then the booleans are formated properly i.e.```T ```becomes ```true``` and ```F``` becomes ```false```, otherwise we issue a deprecation notice.

In the far future, when all clients will have migrated to using the extra formating param, we can make it the default behavior and remove the param.

**Comment by schleichardt** [comment]
So can I just add `formatBooleanFacet=true` to every search request? Or at least the ones with facets?

**Comment by schleichardt** [comment]
@lauraluiz This might also interest you.

**Comment by agourlay** [comment]
It is possible although the optimal solution would be to add it only to the search facets query targetting boolean attribute.
If it is sent it for any other request it will be ignored anyway.

Don't forget to change as well the way boolean facets results are deserialized.

**Pull request merged**
